### ISSUE TITLE
[Deepak Foundation] Move decision logic changes to live app

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Deepak-Foundation#17]
- [x] Move following story changes to live app
https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/deepak-foundation/15
- [x] Run the script required to make change in existing observations
- [ ] Perform sanity testing

**Comment by vedfordev** [comment]
### Developer's Note :

---
**Documents :**
[Bundle Before upload](https://app.zenhub.com/files/639871834/e665c4c3-dd85-4952-a1c5-d12739b630ed/download)

**Task Performed by dev:**
1. Uploaded bundle from uat(Deepak foundation - Adolescent tracking trial) to prod(Deepak Foundation - Adolescent Anaemia tracking)
2. Executed script with making changes in role setting, user and name of org in uat queries
[Refrence](https://gist.github.com/BEULAHEVANJALIN/a9f8705322fe9456e3c9b5c1cd2aeb52)
[Main](https://gist.github.com/vedfordev/e4f7c7451eca11f0a592eaca7ce5de38)

**Comment by Dinesh2019** [comment]
we can able to see a card more than once in the dashboard (issue is gort fixed)

![image_2023_08_10T13_11_35_058Z-min.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/13697e72-a416-4dc5-ae09-6e130c26067d)

Know prod issue: gender search in the search filter will not select or deselected properly 
https://github.com/avniproject/avni-client/issues/1055

**Comment by vedfordev** [comment]
@nupoorkhandelwal deletion of card not worked. Voided  dashboard_section_card_mapping as per uat org
