### ISSUE TITLE
Set up new org for Deepak Foundation - Adolescent tracking program

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Deepak-Foundation#2]
- [x] **Create a new organization**  
**Title** - Deepak foundation - Adolescent tracking
**User suffix** - @dfad 
- [x] Enable ETL
- [x] Keep languages as English and Gujarati in configuration.
- [x] Location Hierarchy - District, Block, Village and School
- [x] Add following users:
utkarsh@dfad - 9900310515 - utkarshh@samanvayfoundation.org - Org Admin

**Comment by Gojo-Taqi** [comment]
ETC 10 mins

**Comment by Gojo-Taqi** [comment]
@utkarshavni created org with name :- **Deepak foundation - Adolescent tracking trail**
It's suffix is :- **dfad_trial**
